### ISSUE TITLE
fatal: unable to access 'https://github.com/open-mmlab/mmdetection.git/': Could not resolve host: github.com

### ISSUE THREAD

**Issue by sarimmehdi** [open-mmlab/mim#101]
When I do `mim install mmdet`, I get the following error:

```
installing mmdet from https://github.com/open-mmlab/mmdetection.git.
Cloning into '/tmp/tmpkmwtxjzz/mmdetection'...
fatal: unable to access 'https://github.com/open-mmlab/mmdetection.git/': Could not resolve host: github.com
Traceback (most recent call last):
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/mim/utils/utils.py", line 418, in call_command
    subprocess.check_call(cmd)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['git', 'clone', 'https://github.com/open-mmlab/mmdetection.git', '-b', 'v2.20.0', '/tmp/tmpkmwtxjzz/mmdetection']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/muhammadmehdi/anaconda3/envs/memex/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/mim/commands/install.py", line 107, in cli
    is_editable=is_editable)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/mim/commands/install.py", line 206, in install
    is_yes, is_user_dir, is_install_master)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/mim/commands/install.py", line 534, in install_from_github
    call_command(clone_cmd)
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/mim/utils/utils.py", line 420, in call_command
    raise highlighted_error(e)  # type: ignore
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/mim/utils/utils.py", line 392, in highlighted_error
    return click.style(msg, fg='red', bold=True)  # type: ignore
  File "/home/muhammadmehdi/anaconda3/envs/memex/lib/python3.7/site-packages/click/termui.py", line 519, in style
    return "".join(bits)
TypeError: sequence item 2: expected str instance, CalledProcessError found
```

**Comment by zhouzaida** [comment]
Hi @sarimmehdi , could you provide the output of `curl -v github.com`? It seems like your machine can not resolve the github.com.

**Comment by sarimmehdi** [comment]
As I have mentioned before, I have no trouble connecting to Github if I just use git but I am unable to do the same with mim. Regardless, I was able to install mmcv without mim. Anyways, here is the output for `curl -v github.com`:

```
*   Trying 140.82.121.4:80...
* TCP_NODELAY set
* Connected to github.com (140.82.121.4) port 80 (#0)
> GET / HTTP/1.1
> Host: github.com
> User-Agent: curl/7.68.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 301 Moved Permanently
< Content-Length: 0
< Location: https://github.com/
< 
* Connection #0 to host github.com left intact
```

**Comment by zhouzaida** [comment]
Hi, sorry for my late reply. This error has been resolved. You can install the main branch to fix the error.
