### ISSUE TITLE
ValueError: Can't determine a unique package given abbreviation resnet18_8xb16_cifar10.py

### ISSUE THREAD

**Issue by LilySys** [open-mmlab/mim#119]
Hi , when i run "mim train resnet18_8xb16_cifar10.py --work-dir tmp --gpus 4 --launcher pytorch", I got the following error:
Traceback (most recent call last):
  File "/home/wenli/anaconda3/envs/pytorch1.7_py37/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/wenli/anaconda3/envs/pytorch1.7_py37/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/wenli/anaconda3/envs/pytorch1.7_py37/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/wenli/anaconda3/envs/pytorch1.7_py37/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/wenli/anaconda3/envs/pytorch1.7_py37/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wenli/anaconda3/envs/pytorch1.7_py37/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/wenli/anaconda3/envs/pytorch1.7_py37/lib/python3.7/site-packages/mim/commands/train.py", line 107, in cli
    other_args=other_args)
  File "/home/wenli/anaconda3/envs/pytorch1.7_py37/lib/python3.7/site-packages/mim/commands/train.py", line 156, in train
    raise ValueError(highlighted_error(msg))
ValueError: Can't determine a unique package given abbreviation resnet18_8xb16_cifar10.py

How can i solve it?

**Comment by LilySys** [comment]
1

**Comment by LilySys** [comment]
solved
