### ISSUE TITLE
unrecognized arguments: --local_rank

### ISSUE THREAD

**Issue by mitming** [open-mmlab/mim#122]
When I run the example
```
mim train mmcls resnet101_b16x8_cifar10.py --work-dir tmp --gpus 4 --launcher pytorch
```

An error happened:

```
Training command is python -m torch.distributed.launch --nproc_per_node=4 --master_port=27803 /home/tiger/.local/lib/python3.7/site-packages/mmcls/.mim/tools/train.py /home/tiger/.local/lib/python3.7/site-packages/mmcls/.mim/configs/resnet/resnet101_b16x8_cifar10.py --launcher pytorch --work-dir tmp.

usage: train.py [-h] [--work-dir WORK_DIR] [--resume-from RESUME_FROM]
                [--no-validate]
                [--device DEVICE | --gpus GPUS | --gpu-ids GPU_IDS [GPU_IDS ...]
                | --gpu-id GPU_ID] [--ipu-replicas IPU_REPLICAS] [--seed SEED]
                [--diff-seed] [--deterministic]
                [--cfg-options CFG_OPTIONS [CFG_OPTIONS ...]]
                [--launcher {none,pytorch,slurm,mpi}]
                [--local-rank LOCAL_RANK]
                config
train.py: error: unrecognized arguments: --local_rank=3
```

```
Traceback (most recent call last):
  File "/home/tiger/.local/bin/mim", line 33, in <module>
    sys.exit(load_entry_point('openmim', 'console_scripts', 'mim')())
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tiger/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/tiger/code/mim/mim/commands/train.py", line 108, in cli
    other_args=other_args)
  File "/home/tiger/code/mim/mim/commands/train.py", line 257, in train
    cmd, env=dict(os.environ, MASTER_PORT=str(port)))
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '-m', 'torch.distributed.launch', '--nproc_per_node=4', '--master_port=27803', '/home/tiger/.local/lib/python3.7/site-packages/mmcls/.mim/tools/train.py', '/home/tiger/.local/lib/python3.7/site-packages/mmcls/.mim/configs/resnet/resnet101_b16x8_cifar10.py', '--launcher', 'pytorch', '--work-dir', 'tmp']' returned non-zero exit status 1.
```

**Comment by okotaku** [comment]
https://github.com/open-mmlab/mmclassification/commit/877ea3080a1509e0fedd80dd954f23704a3211f4

Perhaps in the next version of the release, but the PR here will resolve the issue.

**Comment by saurabh-kataria** [comment]
The error will disappear when you use `torchrun` instead of (the deprecated?) `torch.distributed.launch`. In your case `python -m torch.distributed.launch --nproc_per_node=4 --master_port=27803 ...` will be replaced by `torchrun --nproc_per_node=4 --master_port=27803 ...`.

**Comment by Mingzhu-Zhao** [comment]
Try to rebuild firstly use `python setup.py develop', then run your example again.

**Comment by BiboyQG** [comment]
<img width="838" alt="image" src="https://github.com/open-mmlab/mim/assets/125724218/6af7bf37-b3da-43cd-8355-810b1acc81f8">
