### ISSUE TITLE
Any updates in mim for mmlab major version updates?

### ISSUE THREAD

**Issue by okotaku** [open-mmlab/mim#157]
I used mim with mmcls==1.0.0rc0, but it raised an error like following.

```
$mim train mmcls mmclassification/configs/resnet/resnet18_8xb16_cifar10.py
....
train.py: error: unrecognized arguments: --gpus 1
Traceback (most recent call last):
  File "/opt/conda/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/mim/commands/train.py", line 97, in cli
    is_success, msg = train(
  File "/opt/conda/lib/python3.8/site-packages/mim/commands/train.py", line 256, in train
    ret = subprocess.check_call(
  File "/opt/conda/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
....
```

I saw `gpus` was deleted from mmcls/tools/train.py, and there are no branches in mim repo for major updates.
Any prepares?

**Comment by ice-tong** [comment]
Hi @okotaku, thanks for the feedback. We have not updated the mim train / test / grid-search command yet, but we would update it soon.

**Comment by okotaku** [comment]
Thank you, I got it!
