### ISSUE TITLE
TypeError: sequence item 2: expected str instance, CalledProcessError found

### ISSUE THREAD

**Issue by zengqi0730** [open-mmlab/mim#73]
(mmdetection) zq@edu:~$ mim install mmcls==0.12.0
installing mmcls from https://github.com/open-mmlab/mmclassification.git.
Cloning into '/tmp/tmpbmq8_i4b/mmclassification'...
remote: Enumerating objects: 3155, done.
remote: Counting objects: 100% (6/6), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 3155 (delta 1), reused 1 (delta 0), pack-reused 3149
Receiving objects: 100% (3155/3155), 2.80 MiB | 464.00 KiB/s, done.
Resolving deltas: 100% (2045/2045), done.
Note: checking out '27a49a9646aed9b6c465e22b0bfda3aae1dfb779'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Successfully installed dependencies.

Usage:   
  /home/zq/miniconda3/envs/mmdetection/bin/python -m pip install [options] <requirement specifier> [package-index-options] ...
  /home/zq/miniconda3/envs/mmdetection/bin/python -m pip install [options] -r <requirements file> [package-index-options] ...
  /home/zq/miniconda3/envs/mmdetection/bin/python -m pip install [options] [-e] <vcs project url> ...
  /home/zq/miniconda3/envs/mmdetection/bin/python -m pip install [options] [-e] <local project path> ...
  /home/zq/miniconda3/envs/mmdetection/bin/python -m pip install [options] <archive url/path> ...

option --use-feature: invalid choice: 'in-tree-build' (choose from '2020-resolver', 'fast-deps')
Traceback (most recent call last):
  File "/home/zq/miniconda3/envs/mmdetection/lib/python3.8/site-packages/mim/utils/utils.py", line 417, in call_command
    subprocess.check_call(cmd)
  File "/home/zq/miniconda3/envs/mmdetection/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', '-m', 'pip', 'install', '--use-feature=in-tree-build', '/tmp/tmpbmq8_i4b/mmclassification']' returned non-zero exit status 2.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zq/miniconda3/envs/mmdetection/bin/mim", line 8, in <module>
    sys.exit(cli())
  File "/home/zq/miniconda3/envs/mmdetection/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/zq/miniconda3/envs/mmdetection/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/zq/miniconda3/envs/mmdetection/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zq/miniconda3/envs/mmdetection/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zq/miniconda3/envs/mmdetection/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/zq/miniconda3/envs/mmdetection/lib/python3.8/site-packages/mim/commands/install.py", line 100, in cli
    install(
  File "/home/zq/miniconda3/envs/mmdetection/lib/python3.8/site-packages/mim/commands/install.py", line 204, in install
    install_from_github(target_pkg, target_version, find_url, timeout,
  File "/home/zq/miniconda3/envs/mmdetection/lib/python3.8/site-packages/mim/commands/install.py", line 534, in install_from_github
    install_from_repo(
  File "/home/zq/miniconda3/envs/mmdetection/lib/python3.8/site-packages/mim/commands/install.py", line 491, in install_from_repo
    call_command(install_cmd)
  File "/home/zq/miniconda3/envs/mmdetection/lib/python3.8/site-packages/mim/utils/utils.py", line 419, in call_command
    raise highlighted_error(e)  # type: ignore
  File "/home/zq/miniconda3/envs/mmdetection/lib/python3.8/site-packages/mim/utils/utils.py", line 391, in highlighted_error
    return click.style(msg, fg='red', bold=True)  # type: ignore
  File "/home/zq/miniconda3/envs/mmdetection/lib/python3.8/site-packages/click/termui.py", line 519, in style
    return "".join(bits)
TypeError: sequence item 2: expected str instance, CalledProcessError found

**Comment by zhouzaida** [comment]
hi, what is your version of pip? Upgrade your version to 21.1.2 and it will be ok.
